// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Bono
{
    public int Id { get; set; }

    public DateTime Fecha { get; set; }

    public DateTime FechaCarga { get; set; }

    public int Numero { get; set; }

    public int IdOdontologo { get; set; }

    public int IdObraSocial { get; set; }

    public int IdPractica { get; set; }

    public int IdPaciente { get; set; }

    public int IdBonoEstado { get; set; }

    public virtual BonoEstado IdBonoEstadoNavigation { get; set; }

    public virtual ObraSocial IdObraSocialNavigation { get; set; }

    public virtual Odontologo IdOdontologoNavigation { get; set; }

    public virtual Paciente IdPacienteNavigation { get; set; }

    public virtual Practica IdPracticaNavigation { get; set; }
}