// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Domicilio
{
    public int Id { get; set; }

    public string Calle { get; set; }

    public string Numero { get; set; }

    public int IdLocalidad { get; set; }

    public int IdOdontologo { get; set; }

    public virtual Localidad IdLocalidadNavigation { get; set; }

    public virtual Odontologo IdOdontologoNavigation { get; set; }
}