// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Entrega
{
    public int Id { get; set; }

    public int Desde { get; set; }

    public int Hasta { get; set; }

    public int IdObraSocial { get; set; }

    public int IdOdontologo { get; set; }

    public virtual ObraSocial IdObraSocialNavigation { get; set; }

    public virtual Odontologo IdOdontologoNavigation { get; set; }
}