// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Localidad
{
    public int Id { get; set; }

    public int Cp { get; set; }

    public string Descripcion { get; set; }

    public int IdProvincia { get; set; }

    public virtual ICollection<Domicilio> Domicilio { get; set; } = new List<Domicilio>();

    public virtual Provincia IdProvinciaNavigation { get; set; }
}