// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Paciente
{
    public int Id { get; set; }

    public string Apellido { get; set; }

    public string Nombre { get; set; }

    public DateOnly FechaNacimiento { get; set; }

    public int NumAfiliado { get; set; }

    public string Sexo { get; set; }

    public virtual ICollection<Bono> Bono { get; set; } = new List<Bono>();
}