// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Practica
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public int Numero { get; set; }

    public float Valor { get; set; }

    public virtual ICollection<Bono> Bono { get; set; } = new List<Bono>();
}