// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

public partial class Informe4Context : DbContext
{
    public Informe4Context(DbContextOptions<Informe4Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Bono> Bono { get; set; }

    public virtual DbSet<BonoEstado> BonoEstado { get; set; }

    public virtual DbSet<Domicilio> Domicilio { get; set; }

    public virtual DbSet<Entrega> Entrega { get; set; }

    public virtual DbSet<Localidad> Localidad { get; set; }

    public virtual DbSet<ObraSocial> ObraSocial { get; set; }

    public virtual DbSet<Odontologo> Odontologo { get; set; }

    public virtual DbSet<OdontologoEstado> OdontologoEstado { get; set; }

    public virtual DbSet<Paciente> Paciente { get; set; }

    public virtual DbSet<Practica> Practica { get; set; }

    public virtual DbSet<Provincia> Provincia { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bono>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Bono_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 99999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Fecha).HasColumnName("fecha");
            entity.Property(e => e.FechaCarga).HasColumnName("fechaCarga");
            entity.Property(e => e.IdBonoEstado).HasColumnName("idBonoEstado");
            entity.Property(e => e.IdObraSocial).HasColumnName("idObraSocial");
            entity.Property(e => e.IdOdontologo).HasColumnName("idOdontologo");
            entity.Property(e => e.IdPaciente).HasColumnName("idPaciente");
            entity.Property(e => e.IdPractica).HasColumnName("idPractica");
            entity.Property(e => e.Numero).HasColumnName("numero");

            entity.HasOne(d => d.IdBonoEstadoNavigation).WithMany(p => p.Bono)
                .HasForeignKey(d => d.IdBonoEstado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("idBonoEstado");

            entity.HasOne(d => d.IdObraSocialNavigation).WithMany(p => p.Bono)
                .HasForeignKey(d => d.IdObraSocial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("idObraSocial");

            entity.HasOne(d => d.IdOdontologoNavigation).WithMany(p => p.Bono)
                .HasForeignKey(d => d.IdOdontologo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("idOdontologo");

            entity.HasOne(d => d.IdPacienteNavigation).WithMany(p => p.Bono)
                .HasForeignKey(d => d.IdPaciente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("idPaciente");

            entity.HasOne(d => d.IdPracticaNavigation).WithMany(p => p.Bono)
                .HasForeignKey(d => d.IdPractica)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("idPractica");
        });

        modelBuilder.Entity<BonoEstado>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("BonoEstado_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 9999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Domicilio>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Domicilio_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 99999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Calle)
                .IsRequired()
                .HasColumnName("calle");
            entity.Property(e => e.IdLocalidad).HasColumnName("idLocalidad");
            entity.Property(e => e.IdOdontologo).HasColumnName("idOdontologo");
            entity.Property(e => e.Numero)
                .IsRequired()
                .HasColumnName("numero");

            entity.HasOne(d => d.IdLocalidadNavigation).WithMany(p => p.Domicilio)
                .HasForeignKey(d => d.IdLocalidad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("idLocalidad");

            entity.HasOne(d => d.IdOdontologoNavigation).WithMany(p => p.Domicilio)
                .HasForeignKey(d => d.IdOdontologo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("idOdontologo");
        });

        modelBuilder.Entity<Entrega>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Entrega_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 99999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Desde).HasColumnName("desde");
            entity.Property(e => e.Hasta).HasColumnName("hasta");
            entity.Property(e => e.IdObraSocial).HasColumnName("idObraSocial");
            entity.Property(e => e.IdOdontologo).HasColumnName("idOdontologo");

            entity.HasOne(d => d.IdObraSocialNavigation).WithMany(p => p.Entrega)
                .HasForeignKey(d => d.IdObraSocial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("idObraSocial");

            entity.HasOne(d => d.IdOdontologoNavigation).WithMany(p => p.Entrega)
                .HasForeignKey(d => d.IdOdontologo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("idOdontologo");
        });

        modelBuilder.Entity<Localidad>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Localidad_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 99999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Cp).HasColumnName("cp");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasColumnName("descripcion");
            entity.Property(e => e.IdProvincia).HasColumnName("idProvincia");

            entity.HasOne(d => d.IdProvinciaNavigation).WithMany(p => p.Localidad)
                .HasForeignKey(d => d.IdProvincia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("idProvincia");
        });

        modelBuilder.Entity<ObraSocial>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("ObraSocial_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 9999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Odontologo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Odontologo_pkey");

            entity.HasIndex(e => e.IdOdontologoEstado, "Odontologo_idOdontologoEstado_key").IsUnique();

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasColumnName("apellido");
            entity.Property(e => e.Dni).HasColumnName("dni");
            entity.Property(e => e.IdOdontologoEstado).HasColumnName("idOdontologoEstado");
            entity.Property(e => e.Matricula)
                .IsRequired()
                .HasColumnName("matricula");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasColumnName("nombre");

            entity.HasOne(d => d.IdOdontologoEstadoNavigation).WithOne(p => p.Odontologo)
                .HasForeignKey<Odontologo>(d => d.IdOdontologoEstado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("idOdontologoEstado");
        });

        modelBuilder.Entity<OdontologoEstado>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("OdontologoEstado_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Paciente>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Paciente_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 9999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasColumnName("apellido");
            entity.Property(e => e.FechaNacimiento).HasColumnName("fechaNacimiento");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasColumnName("nombre");
            entity.Property(e => e.NumAfiliado).HasColumnName("numAfiliado");
            entity.Property(e => e.Sexo)
                .IsRequired()
                .HasColumnName("sexo");
        });

        modelBuilder.Entity<Practica>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Practica_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 99999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasColumnName("nombre");
            entity.Property(e => e.Numero).HasColumnName("numero");
            entity.Property(e => e.Valor).HasColumnName("valor");
        });

        modelBuilder.Entity<Provincia>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Provincia_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 99999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasColumnName("descripcion");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}